---
- name: samba config file
  template: src=smb.conf.j2 dest={{ samba_config }} owner=root group={{ root_group }} mode=0644
  notify: service samba reload

#- name: ensure service started at boot (FreeBSD)
#  command: sysrc samba_server_enable="YES"
#  when:  ansible_os_family  == 'FreeBSD'

- name: ensure service started
  service: name={{ samba_service_name }} state=started enabled=yes  
  when:
    - ansible_os_family != 'OpenBSD'
#    - ansible_os_family != 'FreeBSD'

- name: ensure service started at boot (OpenBSD)
  command: rcctl enable samba 
  when:  ansible_os_family  == 'OpenBSD'

- name: ensure service started (OpenBSD)
  command: /etc/rc.d/samba start
  when:  ansible_os_family  == 'OpenBSD'
