---
- name: install package (OpenBSD)
  openbsd_pkg: name='{{ samba_pkg }}' state=present
  when:
    - ansible_os_family == 'OpenBSD'

- name: install package (FreeBSD)
  pkgng: name='{{ samba_pkg }}' state=present
  when:
    - ansible_os_family == 'FreeBSD' 
