---
# tasks file for ansible.samba

- name: Gathering OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: 'true'
  tags: [ 'samba' ]

- name: define the samba package
  set_fact:
    samba_pkg: "{{ samba_pkg|default(__samba_pkg) }}" 
  tags: [ 'samba' ]

- include: install.yml
  tags: [ 'samba' ]

- include: configure.yml
  tags: [ 'samba' ]
