---
# handlers file for ansible.samba
- name: service samba reload
  service: name={{ samba_service_name }} state=reloaded enabled=yes
  when: 
    - ansible_os_family != 'OpenBSD' 
#    - ansible_os_family != 'FreeBSD'

- name: service samba reload
  command: /etc/rc.d/samba reload
  when: ansible_os_family == 'OpenBSD' 

#- name: service samba reload
#  command: /usr/local/etc/rc.d/samba_server reload
#  when: ansible_os_family == 'FreeBSD'
